# Generated by Django 3.2.15 on 2022-09-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_meal', '0002_ingredients_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_meal.ingredients'),
        ),
    ]
