# Generated by Django 3.2.15 on 2022-09-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_meal', '0005_auto_20220928_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, choices=[('G', 'Grams'), ('ML', 'Millilitres'), ('TBSP', 'Tablespoon'), ('TSP', 'Teaspoon')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to=settings.AUTH_USER_MODEL),
        ),
    ]
