# Generated by Django 3.2.15 on 2022-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meal', '0006_auto_20220928_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, choices=[('G', 'Grams'), ('ML', 'Millilitres'), ('TBSP', 'Tablespoon'), ('TSP', 'Teaspoon')], default='', max_length=4, null=True),
        ),
    ]
